apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
      - name: hello
        image: python
        command: ["python",  "-c", "print(123)"]
      restartPolicy: Never
  backoffLimit: 4
